### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ilya-shikhaleev** [jho4us/tc-root#1]
Команды из README (./backend/docker-build.sh и ./frontend/docker-build.sh production) не работают, поскольку в sh нет установки текущей директории. Пришлось заходить в папки backend и frontend соответственно.

**Comment by ilya-shikhaleev** [comment]
Установка frontend требует устанавливать npm локально. В таких случаях рекомендуем использовать отдельный контейнер с npm для сборки контейнера с фронтендом.

**Comment by ilya-shikhaleev** [comment]
Контейнер backend собирается из образа FROM golang:latest. Это приводит к тому, что в production контейнере есть утилиты, нужные только для сборки. Лучше собранный бинарный файл складывать в отдельный контейнер. Таким образом получится 2 контейнера - для сборки и для запуска.

**Comment by ilya-shikhaleev** [comment]
"Navigate to localhost:8082 and create tstore_dev database using utf8" - этот пункт вынуждает делать ручную работу. Лучше создавать базу данных скриптом или самим приложением при запуске. При этом, создать базу получилось лишь потому, что пароль к ней хранится в открытом виде. Для тестового задания это приемлемо, в production необходимо шифровать секреты.

**Comment by ilya-shikhaleev** [comment]
mysql/docker-compose.yml
"image: mysql" 
Лучше явно указывать нужную версию mysql и других базовых образов (а еще лучше не просто версию, а hash, например, image: percona/percona-server@sha256:488b0ebe5c374b5795b6a5308294064579f6b9a4f0f56354989ba41d0e0f1faa #from tag 5.7)

**Comment by jho4us** [comment]
> Команды из README (./backend/docker-build.sh и ./frontend/docker-build.sh production) не работают, поскольку в sh нет установки текущей директории. Пришлось заходить в папки backend и frontend соответственно.

Fixed

**Comment by jho4us** [comment]
> Установка frontend требует устанавливать npm локально. В таких случаях рекомендуем использовать отдельный контейнер с npm для сборки контейнера с фронтендом.

Мы же не обсуждали требование cii, соответственно сборка сделана для машины разработчика, а тут без npm никак

fixed

**Comment by jho4us** [comment]
> Контейнер backend собирается из образа FROM golang:latest. Это приводит к тому, что в production контейнере есть утилиты, нужные только для сборки. Лучше собранный бинарный файл складывать в отдельный контейнер. Таким образом получится 2 контейнера - для сборки и для запуска.

Это все понятно - размер контейнера там получается безобразный, поскольку об оптимизации Devops речи не было, то и тратить на это время жалко. Для production я бы собрал вообще на alpine

fixed - new size
jho4us/tc-backend    latest              293f93224490        2 hours ago         11.2MB

**Comment by jho4us** [comment]
> "Navigate to localhost:8082 and create tstore_dev database using utf8" - этот пункт вынуждает делать ручную работу. Лучше создавать базу данных скриптом или самим приложением при запуске. При этом, создать базу получилось лишь потому, что пароль к ней хранится в открытом виде. Для тестового задания это приемлемо, в production необходимо шифровать секреты.

В других readme есть прямая сноска что вопросы АДМИНИСТРИРОВАНИЯ базы данных в данном демо вообще не рассматриваются. Я не счёл нужным вносить DDL в код приложения, ну а про пароль уж и ежу изначально известно, в kubernetes это был бы secret для данного деплоя

**Comment by jho4us** [comment]
> mysql/docker-compose.yml
> "image: mysql"
> Лучше явно указывать нужную версию mysql и других базовых образов (а еще лучше не просто версию, а hash, например, image: percona/percona-server@sha256:488b0ebe5c374b5795b6a5308294064579f6b9a4f0f56354989ba41d0e0f1faa #from tag 5.7)

Для публичного демо излишне
fixed
